package xml.to.sheet.converter.POJOClasses;

import static org.junit.jupiter.api.Assertions.*;

import javax.xml.bind.JAXBException;

import org.junit.jupiter.api.Test;

import xml.to.sheet.converter.ListOfMeasureAndNote;
import xml.to.sheet.converter.POJOClasses.*;

class XmlToJavaTester {
	
	//Guitar Tests
	@Test
	void test1_BendTestPartName() throws JAXBException {
		String xmlString = bendTestHolder();
		ScorePartwise2 sc = XmlToJava.unmarshal(xmlString, ScorePartwise2.class);
		assertTrue(sc.getPartlist().getScorepart().get(0).getPartname().equals("Guitar"));
	}
	
	@Test
	void test1_BendTestNumOfMeasures() throws JAXBException {
		String xmlString = bendTestHolder();
		ScorePartwise2 sc = XmlToJava.unmarshal(xmlString, ScorePartwise2.class);
		assertTrue(ListOfMeasureAndNote.getlistOfMeasures(sc).size()==2);
	}
	
	@Test
	void test1_BendTestNumOfNotes() throws JAXBException {
		String xmlString = bendTestHolder();
		ScorePartwise2 sc = XmlToJava.unmarshal(xmlString, ScorePartwise2.class);
		assertTrue(ListOfMeasureAndNote.getlistOfNotes(sc).size()==8);
	}
	
	@Test
	void test1_BendTestGetFirstNoteInfo() throws JAXBException {
		String xmlString = bendTestHolder();
		ScorePartwise2 sc = XmlToJava.unmarshal(xmlString, ScorePartwise2.class);
		assertTrue(ListOfMeasureAndNote.getlistOfNotes(sc).get(0).getNotations().getTechnical().getFret()==3);
	}
	
	
	//================================================================================================================
	//Drum-set Tests
	@Test
	void test2_PushTestPartName() throws JAXBException {
		String xmlString = PushTestHolder();
		ScorePartwise2 sc = XmlToJava.unmarshal(xmlString, ScorePartwise2.class);
		assertTrue(sc.getPartlist().getScorepart().get(0).getPartname().equals("Drumset"));
	}

	@Test
	void test2_PushTestNumOfMeasures() throws JAXBException {
		String xmlString = PushTestHolder();
		ScorePartwise2 sc = XmlToJava.unmarshal(xmlString, ScorePartwise2.class);
		assertTrue(ListOfMeasureAndNote.getlistOfMeasures(sc).size()==3);
	}
	
	@Test
	void test2_PushTestNumOfNotes() throws JAXBException {
		String xmlString = PushTestHolder();
		ScorePartwise2 sc = XmlToJava.unmarshal(xmlString, ScorePartwise2.class);
		assertTrue(ListOfMeasureAndNote.getlistOfNotes(sc).size()==27);
	}
	
	@Test
	void test2_PushTestGetFirstNoteInfo() throws JAXBException {
		String xmlString = PushTestHolder();
		ScorePartwise2 sc = XmlToJava.unmarshal(xmlString, ScorePartwise2.class);
		assertTrue(ListOfMeasureAndNote.getlistOfNotes(sc).get(0).getNotehead().equals("x"));
	}
	
	//================================================================================================================
	//Bass Tests
	@Test
	void test3_MoneyTestPartName() throws JAXBException {
		String xmlString = MoneyTestHolder();
		ScorePartwise2 sc = XmlToJava.unmarshal(xmlString, ScorePartwise2.class);
		assertTrue(sc.getPartlist().getScorepart().get(0).getPartname().equals("Bass"));
	}
	
	@Test
	void test3_MoneyTestNumOfMeasures() throws JAXBException {
		String xmlString = MoneyTestHolder();
		ScorePartwise2 sc = XmlToJava.unmarshal(xmlString, ScorePartwise2.class);
		assertTrue(ListOfMeasureAndNote.getlistOfMeasures(sc).size()==4);
	}
	
	@Test
	void test3_MoneyTestNumOfNotes() throws JAXBException {
		String xmlString = MoneyTestHolder();
		ScorePartwise2 sc = XmlToJava.unmarshal(xmlString, ScorePartwise2.class);
		assertTrue(ListOfMeasureAndNote.getlistOfNotes(sc).size()==32);
	}
	
	@Test
	void test3_MoneyTestGetFirstNoteInfo() throws JAXBException {
		String xmlString = MoneyTestHolder();
		ScorePartwise2 sc = XmlToJava.unmarshal(xmlString, ScorePartwise2.class);
		assertTrue(ListOfMeasureAndNote.getlistOfNotes(sc).get(0).getNotations().getTechnical().getFret()==2);
	}
	
	//================================================================================================================
	//These methods hold the xml-string to be used to create the parsers in each 
	//corresponding test case
	private String bendTestHolder() {
		return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n"
				+ "<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 3.1 Partwise//EN\" \"http://www.musicxml.org/dtds/partwise.dtd\">\r\n"
				+ "<score-partwise version=\"3.1\">\r\n"
				+ "  <identification>\r\n"
				+ "    <creator type=\"composer\"></creator>\r\n"
				+ "  </identification>\r\n"
				+ "  <part-list>\r\n"
				+ "    <score-part id=\"P1\">\r\n"
				+ "      <part-name>Guitar</part-name>\r\n"
				+ "    </score-part>\r\n"
				+ "  </part-list>\r\n"
				+ "  <part id=\"P1\">\r\n"
				+ "    <measure number=\"1\">\r\n"
				+ "      <attributes>\r\n"
				+ "        <divisions>8</divisions>\r\n"
				+ "        <key>\r\n"
				+ "          <fifths>0</fifths>\r\n"
				+ "        </key>\r\n"
				+ "        <clef>\r\n"
				+ "          <sign>TAB</sign>\r\n"
				+ "          <line>5</line>\r\n"
				+ "        </clef>\r\n"
				+ "        <staff-details>\r\n"
				+ "          <staff-lines>6</staff-lines>\r\n"
				+ "          <staff-tuning line=\"1\">\r\n"
				+ "            <tuning-step>E</tuning-step>\r\n"
				+ "            <tuning-octave>2</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"2\">\r\n"
				+ "            <tuning-step>A</tuning-step>\r\n"
				+ "            <tuning-octave>2</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"3\">\r\n"
				+ "            <tuning-step>D</tuning-step>\r\n"
				+ "            <tuning-octave>3</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"4\">\r\n"
				+ "            <tuning-step>G</tuning-step>\r\n"
				+ "            <tuning-octave>3</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"5\">\r\n"
				+ "            <tuning-step>B</tuning-step>\r\n"
				+ "            <tuning-octave>3</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"6\">\r\n"
				+ "            <tuning-step>E</tuning-step>\r\n"
				+ "            <tuning-octave>4</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "        </staff-details>\r\n"
				+ "      </attributes>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>A</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>16</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>half</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "            <bend>\r\n"
				+ "              <bend-alter>2.0</bend-alter>\r\n"
				+ "            </bend>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>A</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>16</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>half</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"2\">\r\n"
				+ "      <attributes>\r\n"
				+ "        <divisions>16</divisions>\r\n"
				+ "        <key>\r\n"
				+ "          <fifths>0</fifths>\r\n"
				+ "        </key>\r\n"
				+ "      </attributes>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>16</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>4</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>A</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>16</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "            <bend>\r\n"
				+ "              <bend-alter>2.0</bend-alter>\r\n"
				+ "            </bend>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>C</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>16</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>5</fret>\r\n"
				+ "            <bend>\r\n"
				+ "              <bend-alter>1.0</bend-alter>\r\n"
				+ "            </bend>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>F</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>1</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>C</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>1</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>A</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>16</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "            <bend>\r\n"
				+ "              <bend-alter>2.0</bend-alter>\r\n"
				+ "            </bend>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "  </part>\r\n"
				+ "</score-partwise>\r\n"
				+ "";
	}
	
	private String PushTestHolder() {
		return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n"
				+ "<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 3.1 Partwise//EN\" \"http://www.musicxml.org/dtds/partwise.dtd\">\r\n"
				+ "<score-partwise version=\"3.1\">\r\n"
				+ "  <identification>\r\n"
				+ "    <creator type=\"composer\"></creator>\r\n"
				+ "  </identification>\r\n"
				+ "  <part-list>\r\n"
				+ "    <score-part id=\"P1\">\r\n"
				+ "      <part-name>Drumset</part-name>\r\n"
				+ "      <score-instrument id=\"P1-I45\">\r\n"
				+ "        <instrument-name>Pedal Hi-Hat</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <score-instrument id=\"P1-I47\">\r\n"
				+ "        <instrument-name>Open Hi-Hat</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <score-instrument id=\"P1-I44\">\r\n"
				+ "        <instrument-name>High Floor Tom</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <score-instrument id=\"P1-I43\">\r\n"
				+ "        <instrument-name>Closed Hi-Hat</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <score-instrument id=\"P1-I54\">\r\n"
				+ "        <instrument-name>Ride Bell</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <score-instrument id=\"P1-I39\">\r\n"
				+ "        <instrument-name>Snare</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <score-instrument id=\"P1-I53\">\r\n"
				+ "        <instrument-name>Chinese Cymbal 1</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <score-instrument id=\"P1-I42\">\r\n"
				+ "        <instrument-name>Low Floor Tom</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <score-instrument id=\"P1-I52\">\r\n"
				+ "        <instrument-name>Ride Cymbal 1</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <score-instrument id=\"P1-I48\">\r\n"
				+ "        <instrument-name>Low-Mid Tom</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <score-instrument id=\"P1-I46\">\r\n"
				+ "        <instrument-name>Low Tom</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <score-instrument id=\"P1-I36\">\r\n"
				+ "        <instrument-name>Bass Drum 1</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <score-instrument id=\"P1-I50\">\r\n"
				+ "        <instrument-name>Crash Cymbal 1</instrument-name>\r\n"
				+ "      </score-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I45\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>45</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I47\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>47</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I44\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>44</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I43\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>43</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I54\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>54</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I39\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>39</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I53\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>53</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I42\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>42</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I52\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>52</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I48\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>48</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I46\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>46</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I36\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>36</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "      <midi-instrument id=\"P1-I50\">\r\n"
				+ "        <midi-channel>10</midi-channel>\r\n"
				+ "        <midi-program>1</midi-program>\r\n"
				+ "        <midi-unpitched>50</midi-unpitched>\r\n"
				+ "        <volume>78.7402</volume>\r\n"
				+ "        <pan>0</pan>\r\n"
				+ "      </midi-instrument>\r\n"
				+ "    </score-part>\r\n"
				+ "  </part-list>\r\n"
				+ "  <part id=\"P1\">\r\n"
				+ "    <measure number=\"1\">\r\n"
				+ "      <attributes>\r\n"
				+ "        <divisions>16</divisions>\r\n"
				+ "        <key>\r\n"
				+ "          <fifths>0</fifths>\r\n"
				+ "        </key>\r\n"
				+ "        <time>\r\n"
				+ "          <beats>4</beats>\r\n"
				+ "          <beat-type>4</beat-type>\r\n"
				+ "        </time>\r\n"
				+ "        <clef>\r\n"
				+ "          <sign>percussion</sign>\r\n"
				+ "          <line>2</line>\r\n"
				+ "        </clef>\r\n"
				+ "      </attributes>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>A</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I50\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>F</display-step>\r\n"
				+ "          <display-octave>4</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I36\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>C</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I39\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>F</display-step>\r\n"
				+ "          <display-octave>4</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I36\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>C</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I39\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>A</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I50\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "        <notations>\r\n"
				+ "          <tied type=\"start\"/>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>F</display-step>\r\n"
				+ "          <display-octave>4</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I36\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notations>\r\n"
				+ "          <tied type=\"start\"/>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"2\">\r\n"
				+ "      <attributes>\r\n"
				+ "        <divisions>16</divisions>\r\n"
				+ "      </attributes>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>A</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I50\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "        <notations>\r\n"
				+ "          <tied type=\"stop\"/>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>F</display-step>\r\n"
				+ "          <display-octave>4</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I36\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notations>\r\n"
				+ "          <tied type=\"stop\"/>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>C</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I39\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>F</display-step>\r\n"
				+ "          <display-octave>4</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I36\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>C</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I39\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>G</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>8</duration>\r\n"
				+ "        <instrument id=\"P1-I43\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"3\">\r\n"
				+ "      <attributes>\r\n"
				+ "        <divisions>16</divisions>\r\n"
				+ "      </attributes>\r\n"
				+ "      <note>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>A</display-step>\r\n"
				+ "          <display-octave>5</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>64</duration>\r\n"
				+ "        <instrument id=\"P1-I50\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>whole</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "        <notehead>x</notehead>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <unpitched>\r\n"
				+ "          <display-step>F</display-step>\r\n"
				+ "          <display-octave>4</display-octave>\r\n"
				+ "        </unpitched>\r\n"
				+ "        <duration>64</duration>\r\n"
				+ "        <instrument id=\"P1-I36\"/>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>whole</type>\r\n"
				+ "        <stem>up</stem>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "  </part>\r\n"
				+ "</score-partwise>\r\n"
				+ "";
	}
	
	private String MoneyTestHolder() {
		return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n"
				+ "<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 3.1 Partwise//EN\" \"http://www.musicxml.org/dtds/partwise.dtd\">\r\n"
				+ "<score-partwise version=\"3.1\">\r\n"
				+ "  <identification>\r\n"
				+ "    <creator type=\"composer\"></creator>\r\n"
				+ "  </identification>\r\n"
				+ "  <part-list>\r\n"
				+ "    <score-part id=\"P1\">\r\n"
				+ "      <part-name>Bass</part-name>\r\n"
				+ "    </score-part>\r\n"
				+ "  </part-list>\r\n"
				+ "  <part id=\"P1\">\r\n"
				+ "    <measure number=\"1\">\r\n"
				+ "      <attributes>\r\n"
				+ "        <divisions>14</divisions>\r\n"
				+ "        <key>\r\n"
				+ "          <fifths>0</fifths>\r\n"
				+ "        </key>\r\n"
				+ "        <time>\r\n"
				+ "          <beats>7</beats>\r\n"
				+ "          <beat-type>4</beat-type>\r\n"
				+ "        </time>\r\n"
				+ "        <clef>\r\n"
				+ "          <sign>TAB</sign>\r\n"
				+ "          <line>5</line>\r\n"
				+ "        </clef>\r\n"
				+ "        <staff-details>\r\n"
				+ "          <staff-lines>4</staff-lines>\r\n"
				+ "          <staff-tuning line=\"1\">\r\n"
				+ "            <tuning-step>E</tuning-step>\r\n"
				+ "            <tuning-octave>1</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"2\">\r\n"
				+ "            <tuning-step>A</tuning-step>\r\n"
				+ "            <tuning-octave>1</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"3\">\r\n"
				+ "            <tuning-step>D</tuning-step>\r\n"
				+ "            <tuning-octave>2</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"4\">\r\n"
				+ "            <tuning-step>G</tuning-step>\r\n"
				+ "            <tuning-octave>2</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "        </staff-details>\r\n"
				+ "      </attributes>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>7</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>4</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>F</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>7</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>4</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>F</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>A</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>5</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>5</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <barline location=\"left\">\r\n"
				+ "        <bar-style>heavy-light</bar-style>\r\n"
				+ "        <repeat direction=\"forward\"/>\r\n"
				+ "      </barline>\r\n"
				+ "      <barline location=\"right\">\r\n"
				+ "        <bar-style>light-heavy</bar-style>\r\n"
				+ "        <repeat direction=\"backward\" times=\"8\"/>\r\n"
				+ "      </barline>\r\n"
				+ "      <direction placement=\"above\">\r\n"
				+ "        <direction-type>\r\n"
				+ "          <words relative-x=\"0.0\" relative-y=\"0.0\">x8</words>\r\n"
				+ "        </direction-type>\r\n"
				+ "      </direction>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"2\">\r\n"
				+ "      <attributes>\r\n"
				+ "        <divisions>14</divisions>\r\n"
				+ "        <key>\r\n"
				+ "          <fifths>0</fifths>\r\n"
				+ "        </key>\r\n"
				+ "      </attributes>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>F</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>4</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>F</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>4</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>F</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>7</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>4</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>C</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>7</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>4</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>F</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>A</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>5</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>C</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>4</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>F</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>4</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"3\">\r\n"
				+ "      <attributes>\r\n"
				+ "        <divisions>28</divisions>\r\n"
				+ "        <key>\r\n"
				+ "          <fifths>0</fifths>\r\n"
				+ "        </key>\r\n"
				+ "      </attributes>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>F</step>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>28</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>28</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>G</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>28</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>A</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>28</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>28</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>28</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>5</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"4\">\r\n"
				+ "      <attributes>\r\n"
				+ "        <divisions>14</divisions>\r\n"
				+ "        <key>\r\n"
				+ "          <fifths>0</fifths>\r\n"
				+ "        </key>\r\n"
				+ "      </attributes>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>7</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>4</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>F</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>7</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>4</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>F</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>A</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>5</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>1</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>14</duration>\r\n"
				+ "        <voice>1</voice>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>5</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "  </part>\r\n"
				+ "</score-partwise>\r\n"
				+ "";
	}
	
}
